project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Created with [Quarto](https://quarto.org/) • [License](https://creativecommons.org/licenses/by-nc/4.0/)" 
    center: "Copyright © 2023 Victoria Sass"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        menu:
          - text: "CS&SS 508"
            url: https://vsass.github.io/CSSS508
          - text: "Other courses"
            href: teaching.qmd
      - text: "CSSCR Workshops"
        menu:
          - text: "Introduction to R using R Studio"
            href: workshops/intro_r_rstudio.qmd
          - text: "Introduction to Quarto"
            href: workshops/intro_quarto.qmd
          - text: "Data Wrangling in R"
            href: workshops/data_wrangling_r.qmd
    tools: 
    - icon: envelope-at
      href: mailto:vsass@uw.edu
    - icon: google
      href: https://scholar.google.com/citations?user=A3lEdiIAAAAJ&hl=en
    - icon: github 
      href: https://github.com/vsass
    - icon: file-person
      href: Sass_Victoria_CV_2023.pdf

format:
  html:
    theme: 
      - styles.scss 
    grid: 
      sidebar-width: 300px
      body-width: 1000px
    fontsize: 1.1rem
    #css: styles.css
    toc: false
